### ISSUE TITLE
Wrong path for toolbar.ini

### ISSUE THREAD

**Issue by KronosTheLate** [tim-clifford/dracula-xournalpp#3]
Users are instructed to
![image](https://user-images.githubusercontent.com/61620837/192297113-510e164d-4ff3-4d18-a71b-a9eb8eab1f47.png)

However, what actually worked was `~/.config/xournalpp`
![image](https://user-images.githubusercontent.com/61620837/192297177-39e3989b-fa94-4925-813d-f611363aca43.png)

This has been the source of some frustration. I am not sure if it only applies to linux (mint), but should be updated.

**Comment by ugnmura** [comment]
Just had the same problem, on arch.

**Comment by eleanor-clifford** [comment]
Fixed in e39c469, I think this changed in Xournal++ at some point after I first made the repo.

> This has been the source of some frustration. I am not sure if it only applies to linux (mint), but should be updated.

You are right, but [be careful of your tone](https://gist.github.com/richhickey/1563cddea1002958f96e7ba9519972d9)

**Comment by KronosTheLate** [comment]
Thank you for the patch, and the project. I meant no disrespect to the project, but wanted to be clear on this particular issue. Apologies if I caused offense!

**Comment by eleanor-clifford** [comment]
It's ok, you didn't cause offense, and thanks for pointing out the issue.

(I just wanted to highlight that link because it was a bit close to things users sometimes comment like "It's broken. Fix it." or "This thing doesn't work and it's your fault my time was wasted." which can get frustrating and contribute to maintainer burnout.)
